name: demo
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - audioread=2.1.8=py37_1
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - expat=2.2.5=he1b5a44_1004
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py37h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.5=281
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py37hc9558a2_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.1=hf484d3e_1002
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libllvm8=8.0.1=hc9558a2_0
  - libogg=1.3.2=h14c3975_1001
  - libpng=1.6.37=hed695b0_0
  - librosa=0.7.2=py_0
  - libsndfile=1.0.28=hf484d3e_1000
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.5=h14c3975_1001
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.31.0=py37h8b12597_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.5=281
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=py37hfd86e86_0
  - numba=0.47.0=py37hb3f55d8_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1=h7b6447c_0
  - pandas=0.25.3=py37he6710b0_0
  - pcre=8.43=he1b5a44_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - portaudio=19.6.0=h14c3975_2
  - pthread-stubs=0.4=h14c3975_1001
  - pyaudio=0.2.11=py37h14c3975_1
  - pycparser=2.19=py37_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysoundfile=0.10.2=py_1001
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - resampy=0.2.2=py_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.3.2=py37h7c811a0_0
  - setuptools=44.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.2=py37_cu101
  - tornado=6.0.3=py37h516909a_0
  - wheel=0.33.6=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0

